nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#happily_happy '#happily happy' > logs/console_log_#happily_happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/happily_#happy 'happily #happy' > logs/console_log_happily_#happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/happily_happy 'happily happy' > logs/console_log_happily_happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#happily_#sad '#happily #sad' > logs/console_log_#happily_#sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/happily_#sad 'happily #sad' > logs/console_log_happily_#sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#happily_sad '#happily sad' > logs/console_log_#happily_sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/happily_sad 'happily sad' > logs/console_log_happily_sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#happily_#angry '#happily #angry' > logs/console_log_#happily_#angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#happily_angry '#happily angry' > logs/console_log_#happily_angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/happily_#angry 'happily #angry' > logs/console_log_happily_#angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/happily_angry 'happily angry' > logs/console_log_happily_angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#happily_#fearful '#happily #fearful' > logs/console_log_#happily_#fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/happily_#fearful 'happily #fearful' > logs/console_log_happily_#fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#happily_fearful '#happily fearful' > logs/console_log_#happily_fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/happily_fearful 'happily fearful' > logs/console_log_happily_fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#happily_#surprised '#happily #surprised' > logs/console_log_#happily_#surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/happily_#surprised 'happily #surprised' > logs/console_log_happily_#surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#happily_surprised '#happily surprised' > logs/console_log_#happily_surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/happily_surprised 'happily surprised' > logs/console_log_happily_surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#happily_#disgusted '#happily #disgusted' > logs/console_log_#happily_#disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/happily_#disgusted 'happily #disgusted' > logs/console_log_happily_#disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#happily_disgusted '#happily disgusted' > logs/console_log_#happily_disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/happily_disgusted 'happily disgusted' > logs/console_log_happily_disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#surprisingly_#happy '#surprisingly #happy' > logs/console_log_#surprisingly_#happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/surprisingly_#happy 'surprisingly #happy' > logs/console_log_surprisingly_#happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#surprisingly_happy '#surprisingly happy' > logs/console_log_#surprisingly_happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/surprisingly_happy 'surprisingly happy' > logs/console_log_surprisingly_happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#surprisingly_#sad '#surprisingly #sad' > logs/console_log_#surprisingly_#sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/surprisingly_#sad 'surprisingly #sad' > logs/console_log_surprisingly_#sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#surprisingly_sad '#surprisingly sad' > logs/console_log_#surprisingly_sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/surprisingly_sad 'surprisingly sad' > logs/console_log_surprisingly_sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#surprisingly_#angry '#surprisingly #angry' > logs/console_log_#surprisingly_#angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/surprisingly_angry 'surprisingly angry' > logs/console_log_surprisingly_angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/surprisingly_#angry 'surprisingly #angry' > logs/console_log_surprisingly_#angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/surprisingly_angry 'surprisingly angry' > logs/console_log_surprisingly_angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#surprisingly_#fearful '#surprisingly #fearful' > logs/console_log_#surprisingly_#fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/surprisingly_#fearful 'surprisingly #fearful' > logs/console_log_surprisingly_#fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#surprisingly_fearful '#surprisingly fearful' > logs/console_log_#surprisingly_fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/surprisingly_fearful 'surprisingly fearful' > logs/console_log_surprisingly_fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#surprisingly_#surprised '#surprisingly #surprised' > logs/console_log_#surprisingly_#surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/surprisingly_#surprised 'surprisingly #surprised' > logs/console_log_surprisingly_#surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#surprisingly_surprised '#surprisingly surprised' > logs/console_log_#surprisingly_surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/surprisingly_surprised 'surprisingly surprised' > logs/console_log_surprisingly_surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#surprisingly_#disgusted '#surprisingly #disgusted' > logs/console_log_#surprisingly_#disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/surprisingly_#disgusted 'surprisingly #disgusted' > logs/console_log_surprisingly_#disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#surprisingly_disgusted '#surprisingly disgusted' > logs/console_log_#surprisingly_disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/surprisingly_disgusted 'surprisingly disgusted' > logs/console_log_surprisingly_disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#sadly_#sad '#sadly #sad' > logs/console_log_#sadly_#sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/sadly_#sad 'sadly #sad' > logs/console_log_sadly_#sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#sadly_sad '#sadly sad' > logs/console_log_#sadly_sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/sadly_sad 'sadly sad' > logs/console_log_sadly_sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#sadly_#happy '#sadly #happy' > logs/console_log_#sadly_#happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/sadly_#happy 'sadly #happy' > logs/console_log_sadly_#happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#sadly_happy '#sadly happy' > logs/console_log_#sadly_happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/sadly_happy 'sadly happy' > logs/console_log_sadly_happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#sadly_#angry '#sadly #angry' > logs/console_log_#sadly_#angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/sadly_angry 'sadly angry' > logs/console_log_sadly_angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/sadly_#angry 'sadly #angry' > logs/console_log_sadly_#angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/sadly_angry 'sadly angry' > logs/console_log_sadly_angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#sadly_#fearful '#sadly #fearful' > logs/console_log_#sadly_#fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/sadly_#fearful 'sadly #fearful' > logs/console_log_sadly_#fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#sadly_fearful '#sadly fearful' > logs/console_log_#sadly_fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/sadly_fearful 'sadly fearful' > logs/console_log_sadly_fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#sadly_#surprised '#sadly #surprised' > logs/console_log_#sadly_#surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/sadly_#surprised 'sadly #surprised' > logs/console_log_sadly_#surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#sadly_surprised '#sadly surprised' > logs/console_log_#sadly_surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/sadly_surprised 'sadly surprised' > logs/console_log_sadly_surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#sadly_#disgusted '#sadly #disgusted' > logs/console_log_#sadly_#disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/sadly_#disgusted 'sadly #disgusted' > logs/console_log_sadly_#disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#sadly_disgusted '#sadly disgusted' > logs/console_log_#sadly_disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/sadly_disgusted 'sadly disgusted' > logs/console_log_sadly_disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#angrily_#angry '#angrily #angry' > logs/console_log_#angrily_#angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/angrily_angry 'angrily angry' > logs/console_log_angrily_angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/angrily_#angry 'angrily #angry' > logs/console_log_angrily_#angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/angrily_angry 'angrily angry' > logs/console_log_angrily_angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#angrily_#sad '#angrily #sad' > logs/console_log_#angrily_#sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/angrily_#sad 'angrily #sad' > logs/console_log_angrily_#sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#angrily_sad '#angrily sad' > logs/console_log_#angrily_sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/angrily_sad 'angrily sad' > logs/console_log_angrily_sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#angrily_#happy '#angrily #happy' > logs/console_log_#angrily_#happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/angrily_#happy 'angrily #happy' > logs/console_log_angrily_#happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#angrily_happy '#angrily happy' > logs/console_log_#angrily_happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/angrily_happy 'angrily happy' > logs/console_log_angrily_happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#angrily_#fearful '#angrily #fearful' > logs/console_log_#angrily_#fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/angrily_#fearful 'angrily #fearful' > logs/console_log_angrily_#fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#angrily_fearful '#angrily fearful' > logs/console_log_#angrily_fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/angrily_fearful 'angrily fearful' > logs/console_log_angrily_fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#angrily_#surprised '#angrily #surprised' > logs/console_log_#angrily_#surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/angrily_#surprised 'angrily #surprised' > logs/console_log_angrily_#surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#angrily_surprised '#angrily surprised' > logs/console_log_#angrily_surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/angrily_surprised 'angrily surprised' > logs/console_log_angrily_surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#angrily_#disgusted '#angrily #disgusted' > logs/console_log_#angrily_#disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/angrily_#disgusted 'angrily #disgusted' > logs/console_log_angrily_#disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#angrily_disgusted '#angrily disgusted' > logs/console_log_#angrily_disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/angrily_disgusted 'angrily disgusted' > logs/console_log_angrily_disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#fearfully_#fearful '#fearfully #fearful' > logs/console_log_#fearfully_#fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/fearfully_#fearful 'fearfully #fearful' > logs/console_log_fearfully_#fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#fearfully_fearful '#fearfully fearful' > logs/console_log_#fearfully_fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/fearfully_fearful 'fearfully fearful' > logs/console_log_fearfully_fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#fearfully_#angry '#fearfully #angry' > logs/console_log_#fearfully_#angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/fearfully_angry 'fearfully angry' > logs/console_log_fearfully_angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/fearfully_#angry 'fearfully #angry' > logs/console_log_fearfully_#angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/fearfully_angry 'fearfully angry' > logs/console_log_fearfully_angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#fearfully_#sad '#fearfully #sad' > logs/console_log_#fearfully_#sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/fearfully_#sad 'fearfully #sad' > logs/console_log_fearfully_#sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#fearfully_sad '#fearfully sad' > logs/console_log_#fearfully_sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/fearfully_sad 'fearfully sad' > logs/console_log_fearfully_sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#fearfully_#happy '#fearfully #happy' > logs/console_log_#fearfully_#happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/fearfully_#happy 'fearfully #happy' > logs/console_log_fearfully_#happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#fearfully_happy '#fearfully happy' > logs/console_log_#fearfully_happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/fearfully_happy 'fearfully happy' > logs/console_log_fearfully_happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#fearfully_#surprised '#fearfully #surprised' > logs/console_log_#fearfully_#surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/fearfully_#surprised 'fearfully #surprised' > logs/console_log_fearfully_#surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#fearfully_surprised '#fearfully surprised' > logs/console_log_#fearfully_surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/fearfully_surprised 'fearfully surprised' > logs/console_log_fearfully_surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#fearfully_#disgusted '#fearfully #disgusted' > logs/console_log_#fearfully_#disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/fearfully_#disgusted 'fearfully #disgusted' > logs/console_log_fearfully_#disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#fearfully_disgusted '#fearfully disgusted' > logs/console_log_#fearfully_disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/fearfully_disgusted 'fearfully disgusted' > logs/console_log_fearfully_disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#disgusted_#disgusted '#disgusted #disgusted' > logs/console_log_#disgusted_#disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/disgusted_#disgusted 'disgusted #disgusted' > logs/console_log_disgusted_#disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#disgusted_disgusted '#disgusted disgusted' > logs/console_log_#disgusted_disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/disgusted_disgusted 'disgusted disgusted' > logs/console_log_disgusted_disgusted.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#disgusted_#angry '#disgusted #angry' > logs/console_log_#disgusted_#angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/disgusted_angry 'disgusted angry' > logs/console_log_disgusted_angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/disgusted_#angry 'disgusted #angry' > logs/console_log_disgusted_#angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/disgusted_angry 'disgusted angry' > logs/console_log_disgusted_angry.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#disgusted_#sad '#disgusted #sad' > logs/console_log_#disgusted_#sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/disgusted_#sad 'disgusted #sad' > logs/console_log_disgusted_#sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#disgusted_sad '#disgusted sad' > logs/console_log_#disgusted_sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/disgusted_sad 'disgusted sad' > logs/console_log_disgusted_sad.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#disgusted_#happy '#disgusted #happy' > logs/console_log_#disgusted_#happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/disgusted_#happy 'disgusted #happy' > logs/console_log_disgusted_#happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#disgusted_happy '#disgusted happy' > logs/console_log_#disgusted_happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/disgusted_happy 'disgusted happy' > logs/console_log_disgusted_happy.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#disgusted_#fearful '#disgusted #fearful' > logs/console_log_#disgusted_#fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/disgusted_#fearful 'disgusted #fearful' > logs/console_log_disgusted_#fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#disgusted_fearful '#disgusted fearful' > logs/console_log_#disgusted_fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/disgusted_fearful 'disgusted fearful' > logs/console_log_disgusted_fearful.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#disgusted_#surprised '#disgusted #surprised' > logs/console_log_#disgusted_#surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/disgusted_#surprised 'disgusted #surprised' > logs/console_log_disgusted_#surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/#disgusted_surprised '#disgusted surprised' > logs/console_log_#disgusted_surprised.txt
nice python topsy-crawler.py 1000 10 True CrawledData-29May-1week/disgusted_surprised 'disgusted surprised' > logs/console_log_disgusted_surprised.txt

