nice python ./../topsy-crawler.py 1000 10 True anger/#baseless '#baseless' > logs/console_log_#baseless.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#bait '#bait' > logs/console_log_#bait.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#get_to '#get_to' > logs/console_log_#get_to.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#violent '#violent' > logs/console_log_#violent.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#rebuke '#rebuke' > logs/console_log_#rebuke.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#chide '#chide' > logs/console_log_#chide.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#stormy '#stormy' > logs/console_log_#stormy.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#jaw '#jaw' > logs/console_log_#jaw.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#scold '#scold' > logs/console_log_#scold.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#vex '#vex' > logs/console_log_#vex.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#reproof '#reproof' > logs/console_log_#reproof.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#gravel '#gravel' > logs/console_log_#gravel.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#tempestuous '#tempestuous' > logs/console_log_#tempestuous.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#call_on_the_carpet '#call_on_the_carpet' > logs/console_log_#call_on_the_carpet.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#taunt '#taunt' > logs/console_log_#taunt.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#unfounded '#unfounded' > logs/console_log_#unfounded.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#bedevil '#bedevil' > logs/console_log_#bedevil.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#barbaric '#barbaric' > logs/console_log_#barbaric.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#bothe '#bothe' > logs/console_log_#bothe.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#rile '#rile' > logs/console_log_#rile.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#savage '#savage' > logs/console_log_#savage.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#dress_down '#dress_down' > logs/console_log_#dress_down.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#infuriated '#infuriated' > logs/console_log_#infuriated.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#gaga '#gaga' > logs/console_log_#gaga.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#lecture '#lecture' > logs/console_log_#lecture.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#ferocious '#ferocious' > logs/console_log_#ferocious.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#uncivilized '#uncivilized' > logs/console_log_#uncivilized.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#lambast '#lambast' > logs/console_log_#lambast.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#state_of_nature '#state_of_nature' > logs/console_log_#state_of_nature.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#chafe '#chafe' > logs/console_log_#chafe.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#untamed '#untamed' > logs/console_log_#untamed.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#razz '#razz' > logs/console_log_#razz.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#call_down '#call_down' > logs/console_log_#call_down.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#tease '#tease' > logs/console_log_#tease.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#ramp '#ramp' > logs/console_log_#ramp.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#bawl_out '#bawl_out' > logs/console_log_#bawl_out.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#raving_mad '#raving_mad' > logs/console_log_#raving_mad.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#dotty '#dotty' > logs/console_log_#dotty.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#chew_up '#chew_up' > logs/console_log_#chew_up.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#maddened '#maddened' > logs/console_log_#maddened.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#enraged '#enraged' > logs/console_log_#enraged.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#fantastic '#fantastic' > logs/console_log_#fantastic.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#chew_out '#chew_out' > logs/console_log_#chew_out.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#wilderness '#wilderness' > logs/console_log_#wilderness.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#rampantly '#rampantly' > logs/console_log_#rampantly.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#twit '#twit' > logs/console_log_#twit.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#barbarian '#barbarian' > logs/console_log_#barbarian.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#irritate '#irritate' > logs/console_log_#irritate.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#godforsaken '#godforsaken' > logs/console_log_#godforsaken.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#devil '#devil' > logs/console_log_#devil.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#dun '#dun' > logs/console_log_#dun.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#angry '#angry' > logs/console_log_#angry.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#trounce '#trounce' > logs/console_log_#trounce.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#have_words '#have_words' > logs/console_log_#have_words.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#lambaste '#lambaste' > logs/console_log_#lambaste.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#storm '#storm' > logs/console_log_#storm.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#get_at '#get_at' > logs/console_log_#get_at.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#waste '#waste' > logs/console_log_#waste.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#unwarranted '#unwarranted' > logs/console_log_#unwarranted.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#hazardous '#hazardous' > logs/console_log_#hazardous.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#annoy '#annoy' > logs/console_log_#annoy.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#take_to_task '#take_to_task' > logs/console_log_#take_to_task.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#rage '#rage' > logs/console_log_#rage.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#ride '#ride' > logs/console_log_#ride.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#idle '#idle' > logs/console_log_#idle.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#reprimand '#reprimand' > logs/console_log_#reprimand.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#wild '#wild' > logs/console_log_#wild.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#risky '#risky' > logs/console_log_#risky.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#crucify '#crucify' > logs/console_log_#crucify.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#rag '#rag' > logs/console_log_#rag.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#crazy '#crazy' > logs/console_log_#crazy.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#tantalize '#tantalize' > logs/console_log_#tantalize.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#raging '#raging' > logs/console_log_#raging.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#natural_state '#natural_state' > logs/console_log_#natural_state.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#torment '#torment' > logs/console_log_#torment.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#rally '#rally' > logs/console_log_#rally.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#nettle '#nettle' > logs/console_log_#nettle.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#hot '#hot' > logs/console_log_#hot.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#angered '#angered' > logs/console_log_#angered.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#nark '#nark' > logs/console_log_#nark.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#cod '#cod' > logs/console_log_#cod.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#frustrate '#frustrate' > logs/console_log_#frustrate.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#fierce '#fierce' > logs/console_log_#fierce.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#berate '#berate' > logs/console_log_#berate.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#groundless '#groundless' > logs/console_log_#groundless.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#uncivilised '#uncivilised' > logs/console_log_#uncivilised.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#furious '#furious' > logs/console_log_#furious.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#remonstrate '#remonstrate' > logs/console_log_#remonstrate.txt
nice python ./../topsy-crawler.py 1000 10 True anger/#tantalise '#tantalise' > logs/console_log_#tantalise.txt

