nice python ./../topsy-crawler.py 1000 10 True disgust/#repulse '#repulse' > logs/console_log_#repulse.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#tired_of '#tired_of' > logs/console_log_#tired_of.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#freak '#freak' > logs/console_log_#freak.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#sickish '#sickish' > logs/console_log_#sickish.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#cast '#cast' > logs/console_log_#cast.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#macabre '#macabre' > logs/console_log_#macabre.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#be_sick '#be_sick' > logs/console_log_#be_sick.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#crazy '#crazy' > logs/console_log_#crazy.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#chuck '#chuck' > logs/console_log_#chuck.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#nauseate '#nauseate' > logs/console_log_#nauseate.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#demented '#demented' > logs/console_log_#demented.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#push_back '#push_back' > logs/console_log_#push_back.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#rising '#rising' > logs/console_log_#rising.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#ghastly '#ghastly' > logs/console_log_#ghastly.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#snub '#snub' > logs/console_log_#snub.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#barf '#barf' > logs/console_log_#barf.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#brainsick '#brainsick' > logs/console_log_#brainsick.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#pale '#pale' > logs/console_log_#pale.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#grisly '#grisly' > logs/console_log_#grisly.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#come_down '#come_down' > logs/console_log_#come_down.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#wan '#wan' > logs/console_log_#wan.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#regorge '#regorge' > logs/console_log_#regorge.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#beat_back '#beat_back' > logs/console_log_#beat_back.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#retch '#retch' > logs/console_log_#retch.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#nauseated '#nauseated' > logs/console_log_#nauseated.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/"#turn_one's_stomach" '#turn_one's_stomach' > logs/console_log_#turn_one's_stomach.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#sicken '#sicken' > logs/console_log_#sicken.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#spew '#spew' > logs/console_log_#spew.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#vomit_up '#vomit_up' > logs/console_log_#vomit_up.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#pallid '#pallid' > logs/console_log_#pallid.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#puke '#puke' > logs/console_log_#puke.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#honk '#honk' > logs/console_log_#honk.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#rebellion '#rebellion' > logs/console_log_#rebellion.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#disturbed '#disturbed' > logs/console_log_#disturbed.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#fed_up '#fed_up' > logs/console_log_#fed_up.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#disgust '#disgust' > logs/console_log_#disgust.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#gross_out '#gross_out' > logs/console_log_#gross_out.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#sick_of '#sick_of' > logs/console_log_#sick_of.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#unbalanced '#unbalanced' > logs/console_log_#unbalanced.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#insurrection '#insurrection' > logs/console_log_#insurrection.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#sick '#sick' > logs/console_log_#sick.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#disgorge '#disgorge' > logs/console_log_#disgorge.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#uprising '#uprising' > logs/console_log_#uprising.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#spue '#spue' > logs/console_log_#spue.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#drive_back '#drive_back' > logs/console_log_#drive_back.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#upchuck '#upchuck' > logs/console_log_#upchuck.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#disgusted '#disgusted' > logs/console_log_#disgusted.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#regurgitate '#regurgitate' > logs/console_log_#regurgitate.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#vomit '#vomit' > logs/console_log_#vomit.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#mad '#mad' > logs/console_log_#mad.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#churn_up '#churn_up' > logs/console_log_#churn_up.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#gruesome '#gruesome' > logs/console_log_#gruesome.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#grim '#grim' > logs/console_log_#grim.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#rebuff '#rebuff' > logs/console_log_#rebuff.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#force_back '#force_back' > logs/console_log_#force_back.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#queasy '#queasy' > logs/console_log_#queasy.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#throw_up '#throw_up' > logs/console_log_#throw_up.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#fight_off '#fight_off' > logs/console_log_#fight_off.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#ill '#ill' > logs/console_log_#ill.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#nauseous '#nauseous' > logs/console_log_#nauseous.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#revolt '#revolt' > logs/console_log_#revolt.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#drive '#drive' > logs/console_log_#drive.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#cat '#cat' > logs/console_log_#cat.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#purge '#purge' > logs/console_log_#purge.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#freak_out '#freak_out' > logs/console_log_#freak_out.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#repel '#repel' > logs/console_log_#repel.txt
nice python ./../topsy-crawler.py 1000 10 True disgust/#unhinged '#unhinged' > logs/console_log_#unhinged.txt

