#nice python ./../topsy-crawler.py 1000 5 True fear/#atrocious '#atrocious' > logs/console_log_#atrocious.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#horrific '#horrific' > logs/console_log_#horrific.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#cowardly '#cowardly' > logs/console_log_#cowardly.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#awesome '#awesome' > logs/console_log_#awesome.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#affright '#affright' > logs/console_log_#affright.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#awfully '#awfully' > logs/console_log_#awfully.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#desperate '#desperate' > logs/console_log_#desperate.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#horrendous '#horrendous' > logs/console_log_#horrendous.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#abominable '#abominable' > logs/console_log_#abominable.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#fea '#fea' > logs/console_log_#fea.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#fearsome '#fearsome' > logs/console_log_#fearsome.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#dreadful '#dreadful' > logs/console_log_#dreadful.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#fright '#fright' > logs/console_log_#fright.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#horrid '#horrid' > logs/console_log_#horrid.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#ugly '#ugly' > logs/console_log_#ugly.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#tremendous '#tremendous' > logs/console_log_#tremendous.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#awed '#awed' > logs/console_log_#awed.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#severe '#severe' > logs/console_log_#severe.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#amazing '#amazing' > logs/console_log_#amazing.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#frighten '#frighten' > logs/console_log_#frighten.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#dreaded '#dreaded' > logs/console_log_#dreaded.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#painful '#painful' > logs/console_log_#painful.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#wicked '#wicked' > logs/console_log_#wicked.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#outrageous '#outrageous' > logs/console_log_#outrageous.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#terrorisation '#terrorisation' > logs/console_log_#terrorisation.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#horrible '#horrible' > logs/console_log_#horrible.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#awing '#awing' > logs/console_log_#awing.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#dire '#dire' > logs/console_log_#dire.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#awful '#awful' > logs/console_log_#awful.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#awe-inspiring '#awe-inspiring' > logs/console_log_#awe-inspiring.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#nasty '#nasty' > logs/console_log_#nasty.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#frightening '#frightening' > logs/console_log_#frightening.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#frightful '#frightful' > logs/console_log_#frightful.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#apprehension '#apprehension' > logs/console_log_#apprehension.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#horrifying '#horrifying' > logs/console_log_#horrifying.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#direful '#direful' > logs/console_log_#direful.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#frightfully '#frightfully' > logs/console_log_#frightfully.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#fearful '#fearful' > logs/console_log_#fearful.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#hideous '#hideous' > logs/console_log_#hideous.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#terrible '#terrible' > logs/console_log_#terrible.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#timorous '#timorous' > logs/console_log_#timorous.txt
#nice python ./../topsy-crawler.py 1000 5 True fear/#terribly '#terribly' > logs/console_log_#terribly.txt
nice python ./../topsy-crawler.py 1000 5 True fear/#apprehensiveness '#apprehensiveness' > logs/console_log_#apprehensiveness.txt
nice python ./../topsy-crawler.py 1000 5 True fear/#dread '#dread' > logs/console_log_#dread.txt
nice python ./../topsy-crawler.py 1000 5 True fear/#trepid '#trepid' > logs/console_log_#trepid.txt
nice python ./../topsy-crawler.py 1000 5 True fear/#terrorization '#terrorization' > logs/console_log_#terrorization.txt
nice python ./../topsy-crawler.py 1000 5 True fear/#scare '#scare' > logs/console_log_#scare.txt
nice python ./../topsy-crawler.py 1000 5 True fear/#unspeakable '#unspeakable' > logs/console_log_#unspeakable.txt

