nice python ./../topsy-crawler.py 1000 10 True indifferent/#deafen '#deafen' > logs/console_log_#deafen.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#soggy '#soggy' > logs/console_log_#soggy.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#deaf '#deaf' > logs/console_log_#deaf.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#unbiased '#unbiased' > logs/console_log_#unbiased.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#incorporeal '#incorporeal' > logs/console_log_#incorporeal.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#indifferent '#indifferent' > logs/console_log_#indifferent.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#tolerably '#tolerably' > logs/console_log_#tolerably.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#extraneous '#extraneous' > logs/console_log_#extraneous.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#achromatic '#achromatic' > logs/console_log_#achromatic.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#sluggish '#sluggish' > logs/console_log_#sluggish.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#apathetic '#apathetic' > logs/console_log_#apathetic.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#inert '#inert' > logs/console_log_#inert.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#orthogonal '#orthogonal' > logs/console_log_#orthogonal.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#torpid '#torpid' > logs/console_log_#torpid.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#neutral '#neutral' > logs/console_log_#neutral.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#acceptably '#acceptably' > logs/console_log_#acceptably.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#electroneutral '#electroneutral' > logs/console_log_#electroneutral.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#nonmaterial '#nonmaterial' > logs/console_log_#nonmaterial.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#immaterial '#immaterial' > logs/console_log_#immaterial.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#impersonal '#impersonal' > logs/console_log_#impersonal.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#so-so '#so-so' > logs/console_log_#so-so.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#unbiassed '#unbiassed' > logs/console_log_#unbiassed.txt
nice python ./../topsy-crawler.py 1000 10 True indifferent/#impertinent '#impertinent' > logs/console_log_#impertinent.txt

