nice python ./../topsy-crawler.py 1000 10 True negative/#prohibit '#prohibit' > logs/console_log_#prohibit.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#forbid '#forbid' > logs/console_log_#forbid.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#blackball '#blackball' > logs/console_log_#blackball.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#damage '#damage' > logs/console_log_#damage.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#invalidating '#invalidating' > logs/console_log_#invalidating.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#ostracise '#ostracise' > logs/console_log_#ostracise.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#ostracize '#ostracize' > logs/console_log_#ostracize.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#negative '#negative' > logs/console_log_#negative.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#negatively_charged '#negatively_charged' > logs/console_log_#negatively_charged.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#prejudicial '#prejudicial' > logs/console_log_#prejudicial.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#detrimental '#detrimental' > logs/console_log_#detrimental.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#prejudicious '#prejudicious' > logs/console_log_#prejudicious.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#electronegative '#electronegative' > logs/console_log_#electronegative.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#veto '#veto' > logs/console_log_#veto.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#proscribe '#proscribe' > logs/console_log_#proscribe.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#disallow '#disallow' > logs/console_log_#disallow.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#nix '#nix' > logs/console_log_#nix.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#interdict '#interdict' > logs/console_log_#interdict.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#cast_out '#cast_out' > logs/console_log_#cast_out.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#subtraction '#subtraction' > logs/console_log_#subtraction.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#shun '#shun' > logs/console_log_#shun.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#banish '#banish' > logs/console_log_#banish.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#barring '#barring' > logs/console_log_#barring.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#damaging '#damaging' > logs/console_log_#damaging.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#ban '#ban' > logs/console_log_#ban.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#disconfirming '#disconfirming' > logs/console_log_#disconfirming.txt
nice python ./../topsy-crawler.py 1000 10 True negative/#minus '#minus' > logs/console_log_#minus.txt

