nice python ./../topsy-crawler.py 1000 10 True positive/#positively_charged '#positively_charged' > logs/console_log_#positively_charged.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#positive_degree '#positive_degree' > logs/console_log_#positive_degree.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#substantiative '#substantiative' > logs/console_log_#substantiative.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#reassert '#reassert' > logs/console_log_#reassert.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#demonstrable '#demonstrable' > logs/console_log_#demonstrable.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#decreed '#decreed' > logs/console_log_#decreed.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#corroborate '#corroborate' > logs/console_log_#corroborate.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#substantiating '#substantiating' > logs/console_log_#substantiating.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#dictate '#dictate' > logs/console_log_#dictate.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#summation '#summation' > logs/console_log_#summation.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#overconfident '#overconfident' > logs/console_log_#overconfident.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#irrefutable '#irrefutable' > logs/console_log_#irrefutable.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#validatory '#validatory' > logs/console_log_#validatory.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#confirmative '#confirmative' > logs/console_log_#confirmative.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#rationalist '#rationalist' > logs/console_log_#rationalist.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#sure-footed '#sure-footed' > logs/console_log_#sure-footed.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#confirm '#confirm' > logs/console_log_#confirm.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#addition '#addition' > logs/console_log_#addition.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#positive '#positive' > logs/console_log_#positive.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#support '#support' > logs/console_log_#support.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#corroboratory '#corroboratory' > logs/console_log_#corroboratory.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#confident '#confident' > logs/console_log_#confident.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#confirming '#confirming' > logs/console_log_#confirming.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#sustain '#sustain' > logs/console_log_#sustain.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#asset '#asset' > logs/console_log_#asset.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#corroborative '#corroborative' > logs/console_log_#corroborative.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#surefooted '#surefooted' > logs/console_log_#surefooted.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#ordained '#ordained' > logs/console_log_#ordained.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#collateral '#collateral' > logs/console_log_#collateral.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#verificatory '#verificatory' > logs/console_log_#verificatory.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#prescribe '#prescribe' > logs/console_log_#prescribe.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#positivist '#positivist' > logs/console_log_#positivist.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#incontrovertible '#incontrovertible' > logs/console_log_#incontrovertible.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#positivistic '#positivistic' > logs/console_log_#positivistic.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#appointed '#appointed' > logs/console_log_#appointed.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#prescribed '#prescribed' > logs/console_log_#prescribed.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#convert '#convert' > logs/console_log_#convert.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#win_ove '#win_ove' > logs/console_log_#win_ove.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#affirm '#affirm' > logs/console_log_#affirm.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#convinced '#convinced' > logs/console_log_#convinced.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#substantiate '#substantiate' > logs/console_log_#substantiate.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#official '#official' > logs/console_log_#official.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#confirmatory '#confirmatory' > logs/console_log_#confirmatory.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#orde '#orde' > logs/console_log_#orde.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#verifying '#verifying' > logs/console_log_#verifying.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#electropositive '#electropositive' > logs/console_log_#electropositive.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#convince '#convince' > logs/console_log_#convince.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#plus '#plus' > logs/console_log_#plus.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#cocksure '#cocksure' > logs/console_log_#cocksure.txt
nice python ./../topsy-crawler.py 1000 10 True positive/#validating '#validating' > logs/console_log_#validating.txt

