nice python ./../topsy-crawler.py 1000 10 True sadness/#distress '#distress' > logs/console_log_#distress.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#reprehensible '#reprehensible' > logs/console_log_#reprehensible.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#drab '#drab' > logs/console_log_#drab.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#no-good '#no-good' > logs/console_log_#no-good.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#sad '#sad' > logs/console_log_#sad.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#perturbing '#perturbing' > logs/console_log_#perturbing.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#pitiable '#pitiable' > logs/console_log_#pitiable.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#miserable '#miserable' > logs/console_log_#miserable.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#disturbing '#disturbing' > logs/console_log_#disturbing.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#no-count '#no-count' > logs/console_log_#no-count.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#worrisome '#worrisome' > logs/console_log_#worrisome.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#distressing '#distressing' > logs/console_log_#distressing.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#hapless '#hapless' > logs/console_log_#hapless.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#disconsolate '#disconsolate' > logs/console_log_#disconsolate.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#lamentable '#lamentable' > logs/console_log_#lamentable.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#troubling '#troubling' > logs/console_log_#troubling.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#woeful '#woeful' > logs/console_log_#woeful.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#criminal '#criminal' > logs/console_log_#criminal.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#poo '#poo' > logs/console_log_#poo.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#blue '#blue' > logs/console_log_#blue.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#wretched '#wretched' > logs/console_log_#wretched.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#distressful '#distressful' > logs/console_log_#distressful.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#pathetic '#pathetic' > logs/console_log_#pathetic.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#vicious '#vicious' > logs/console_log_#vicious.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#good-for-naught '#good-for-naught' > logs/console_log_#good-for-naught.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#regretful '#regretful' > logs/console_log_#regretful.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#dark '#dark' > logs/console_log_#dark.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#sorry '#sorry' > logs/console_log_#sorry.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#dismal '#dismal' > logs/console_log_#dismal.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#misfortunate '#misfortunate' > logs/console_log_#misfortunate.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#condemnable '#condemnable' > logs/console_log_#condemnable.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#pitiful '#pitiful' > logs/console_log_#pitiful.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#grim '#grim' > logs/console_log_#grim.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#straiten '#straiten' > logs/console_log_#straiten.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#execrable '#execrable' > logs/console_log_#execrable.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#drea '#drea' > logs/console_log_#drea.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#meritless '#meritless' > logs/console_log_#meritless.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#dreary '#dreary' > logs/console_log_#dreary.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#no-account '#no-account' > logs/console_log_#no-account.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#good-for-nothing '#good-for-nothing' > logs/console_log_#good-for-nothing.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#dingy '#dingy' > logs/console_log_#dingy.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#bad '#bad' > logs/console_log_#bad.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#gloomy '#gloomy' > logs/console_log_#gloomy.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#piteous '#piteous' > logs/console_log_#piteous.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#deplorable '#deplorable' > logs/console_log_#deplorable.txt
nice python ./../topsy-crawler.py 1000 10 True sadness/#worrying '#worrying' > logs/console_log_#worrying.txt

